#import "template.typ": *

#show: project

#title()
#index()
#insert("template.h")
#insert(".bashrc")
#insert(".vimrc")
#insert("binary_search.h")
= Data Structures
#insert("ds/hashmap.h")
#insert("ds/order_statistic_tree.h")
#insert("ds/uf.h")
#insert("ds/convex_hull_trick.h")
#insert("ds/compress_coords.h")
#insert("ds/op.h")
#insert("ds/sparse_table.h")
#insert("ds/iterative_segment_tree.h")
#insert("ds/fenwick_tree.h")
#insert("ds/compressed_fenwick_tree_2d.h")
#insert("ds/recursive_segment_tree.h")
#insert("ds/persistent_segment_tree.h")
#insert("ds/tag.h")
#insert("ds/lazy_segment_tree.h")
#insert("ds/dynamic_lazy_segment_tree.h")
#insert("ds/persistent_lazy_segment_tree.h")
#insert("ds/treap_node.h")
#insert("ds/treap.h")
#insert("ds/mo.h")
= Number Theory
// #insert("nt/mod_pow.h")
#insert("nt/modmul_ll.h")
#insert("nt/miller_rabin.h")
#insert("nt/factor.h")
#insert("nt/mod_arithmetic.h")
#insert("nt/ntt.h")
= Geometry
#insert("geometry/point.h")
#insert("geometry/side_of.h")
#insert("geometry/line_intersection.h")
#insert("geometry/closest_pair.h")
#insert("geometry/convex_hull.h")
#insert("geometry/minkowski.h")
#insert("geometry/halfplane_intersection.h")
= Strings
#insert("strings/suffix_array.h")
#insert("strings/kmp.h")
= Graphs
#insert("graph/topo_sort.h")
#insert("graph/scc.h")
#insert("graph/lca.h")
#insert("graph/binary_lifting.h")
#insert("graph/hopcroft_karp.h")
#insert("graph/dinic.h")
#insert("graph/push_relabel.h")
#insert("graph/maxflow_with_demands.h")
#insert("graph/mcmf.h")
#insert("graph/weighted_matching.h")
